// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzP6i6QEoUMkfvB5szG-vhm8IQMBapitk',
    appId: '1:53875487406:web:f8a65052062c25dbebb33f',
    messagingSenderId: '53875487406',
    projectId: 'bdcrudflashcards',
    authDomain: 'bdcrudflashcards.firebaseapp.com',
    storageBucket: 'bdcrudflashcards.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd9VkVdpKDYFQCIVwQZ7c--eCsjUFjBGc',
    appId: '1:53875487406:android:b868d02f506e232cebb33f',
    messagingSenderId: '53875487406',
    projectId: 'bdcrudflashcards',
    storageBucket: 'bdcrudflashcards.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAymx6KDOGSJt7W8gp7Ph6F1l2IZE_jn8U',
    appId: '1:53875487406:ios:9ce567482a6476e4ebb33f',
    messagingSenderId: '53875487406',
    projectId: 'bdcrudflashcards',
    storageBucket: 'bdcrudflashcards.firebasestorage.app',
    iosBundleId: 'com.crud_flashcards',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAymx6KDOGSJt7W8gp7Ph6F1l2IZE_jn8U',
    appId: '1:53875487406:ios:9ce567482a6476e4ebb33f',
    messagingSenderId: '53875487406',
    projectId: 'bdcrudflashcards',
    storageBucket: 'bdcrudflashcards.firebasestorage.app',
    iosBundleId: 'com.crud_flashcards',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzP6i6QEoUMkfvB5szG-vhm8IQMBapitk',
    appId: '1:53875487406:web:5912fa2cc3aa3a4cebb33f',
    messagingSenderId: '53875487406',
    projectId: 'bdcrudflashcards',
    authDomain: 'bdcrudflashcards.firebaseapp.com',
    storageBucket: 'bdcrudflashcards.firebasestorage.app',
  );
}
